#pragma once
#include "iostream"
using namespace std;
void moshahedegs();
void editfoodsname();
void editfoodsgeimat();
void editfoorshazf();
void newfoots();
void moshahedegk();
void newfootk();
void editfootkname();
void editfootkgeimat();
void editfootkhazf();
void shows();
void adds();
void changeusrs();
void changepsws();
void hazfusrs();
void showk();
void addk();
void changeusrk();
void changepswk();
void hazfusrk();
void etebars(string s);
void rezervs(string s);
void profilenames(string s);
void changepsws(string s);
void moshahedegk();
void rezervk(string s);
void etebark(string s);
void profilenamek(string s);
void changepswk(string s);
void resids();
void residk();
void rezerv();
void backup(int s,int y);
void bazgardany(int s, int y);
void showrezervs(string s);
void showrezervk(string s);